CREATE DATABASE SISTVENTAS;
GO
USE SISTVENTAS;
GO

CREATE TABLE EMPLEADO
( 
	IDEMPLEADO           integer IDENTITY ( 1,1 ) ,
	NOMBRE               varchar(100)  NOT NULL ,
	APELLIDO             varchar(100)  NOT NULL ,
	CORREO               varchar(60)  NOT NULL ,
	TELEFONO             varchar(20)  NOT NULL ,
	ACTIVO               integer  NOT NULL 
	CONSTRAINT DF_EMPLEADO_ACTIVO
		 DEFAULT  1
	CONSTRAINT CK_EMPLEADO_ACTIVO
		CHECK  ( [ACTIVO]=0 OR [ACTIVO]=1 ),
	CONSTRAINT XPKEMPLEADO PRIMARY KEY (IDEMPLEADO ASC)
)
go



CREATE TABLE ROL
( 
	IDROL                integer  NOT NULL ,
	NOMBRE               varchar(60)  NOT NULL ,
	CONSTRAINT XPKROL PRIMARY KEY (IDROL ASC)
)
go



CREATE TABLE USUARIO
( 
	IDEMPLEADO           integer  NOT NULL ,
	USUARIO              varchar(60)  NOT NULL ,
	CLAVE                varchar(60)  NOT NULL ,
	IDROL                integer  NOT NULL ,
	ACTIVO               integer  NOT NULL 
	CONSTRAINT DF_USUARIO_ACTIVO
		 DEFAULT  1
	CONSTRAINT CK_USUARIO_ACTIVO
		CHECK  ( [ACTIVO]=0 OR [ACTIVO]=1 ),
	CONSTRAINT XPKUSUARIO PRIMARY KEY (IDEMPLEADO ASC),
	CONSTRAINT FK_USUARIO_EMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO(IDEMPLEADO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION,
CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (IDROL) REFERENCES ROL(IDROL)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
go


-- DATOS

SET IDENTITY_INSERT EMPLEADO ON;
GO

INSERT INTO EMPLEADO(IDEMPLEADO, NOMBRE, APELLIDO, CORREO, TELEFONO,ACTIVO)
VALUES(1, 'KEVIN DENIZ', 'PAUCAR FUENTES', 'kevinpf@gmail.com', '981773114',1);
GO

INSERT INTO EMPLEADO(IDEMPLEADO, NOMBRE, APELLIDO, CORREO, TELEFONO,ACTIVO)
VALUES(2, 'NATALY', 'SALCEDO GUERRA', 'nsalcedog@gmail.com', '987811884',1);
GO



SET IDENTITY_INSERT EMPLEADO OFF;
GO




INSERT INTO ROL(IDROL, NOMBRE) VALUES( 1, 'OPERADOR' );
INSERT INTO ROL(IDROL, NOMBRE) VALUES( 2, 'ADMINISTRADOR' );

GO


INSERT INTO USUARIO(IDEMPLEADO, USUARIO, CLAVE, IDROL,ACTIVO) VALUES(1, 'kevinpf', '12345', 1,1);
INSERT INTO USUARIO(IDEMPLEADO, USUARIO, CLAVE, IDROL,ACTIVO) VALUES(2, 'natsalcedo', 'nasague', 2,1);
go

select u.IDEMPLEADO, u.USUARIO, '*****' CLAVE, 
u.IDROL, r.NOMBRE
from dbo.USUARIO u
join dbo.EMPLEADO e on u.IDEMPLEADO = e.IDEMPLEADO
join dbo.ROL r on u.IDROL = r.IDROL
where u.USUARIO = 'kevinpf' and u.CLAVE = '12345'
go



select * from usuario;
go


